import random
mood = random.randrange(0,3)
print("I sense your energy. Your true emotions are coming across my screen.\n")
print("You are...")
if mood == 0:
    print("____________")
    print("|          |")
    print("|  0   0   |")
    print("|    <     |")
    print("| .      . |")
    print("|  .    .  |")
    print("|    ..    |")
    print("------------")
elif mood == 1:
    print("____________")
    print("|          |")
    print("|  0   0   |")
    print("|    <     |")
    print("|          |")
    print("|  ......  |")
    print("|          |")
    print("------------")
elif mood == 2:
    print("____________")
    print("|          |")
    print("|  0   0   |")
    print("|    <     |")
    print("|    ..    |")
    print("|   .  .   |")
    print("|  .    .  |")
    print("------------")
else:
    print("Illegal mood value!")
print("...today.\n")
