print("Totals your monthly spending so that your trust fund doesn't run out\n")
print("<and you're foreced to get a real job>.\n")
print("Please enter the requested, monthly costs. Since you're rich, ignore pennies and use only dollar amounts. \n\n")
tune = input("Lamborghini Tune-Ups: ")
apartment = input("Manhattan Apartment: ")
rental = input("Private Jet Rental: ")
gifs = input("Gifs: ")
dinning = input("Dinning Out: ")
staff = input("Staff <butlers, chef, driver, assistant>: ")
person = input("Personal Guru and Coach: ")
game = input("Computer Games: ")
print("\nGrand Total: ",tune + apartment + rental + gifs + dinning + staff + person + game)
print("\n")
