print("Totals your monthly spending so that your trust fund doesn't run out")
print("<and you're foreced to get a real jon>.")
print("\nPlease enter the requested, monthly costs. Since you're rich, ignore pennies")
print("and use only dollar amounts.\n\n")
print("Lamborghini Tune-Ups: 2000")
print("Manhasttan Apartment: 10000")
print("Private Jet Rental: 17000")
print("Gifts: 5000")
print("Dining Out: 7500")
print("Staff <butlers, chef, driver, assistant>: 12000")
print("Personal Guru and Coach: 6800")
print("Computer Games: 1000\n")
print("Grand Total:  61300\n\n")
print("Press the enter key to exit")
