print("Totals your monthly spending so that your trust fund doesn't run out\n")
print("<and you're foreced to get a real job>.\n")
print("Please enter the requested, monthly costs. Since you're rich, ignore pennies and use only dollar amounts. \n\n")
tune = int(input("Lamborghini Tune-Ups: "))
apartment = int(input("Manhattan Apartment: "))
rental = int(input("Private Jet Rental: "))
gifs = int(input("Gifs: "))
dinning = int(input("Dinning Out: "))
staff = int(input("Staff <butlers, chef, driver, assistant>: "))
person = int(input("Personal Guru and Coach: "))
game = int(input("Computer Games: "))
print("\nGrand Total:   ",tune+apartment+rental+gifs+dinning+staff+person+game)
print("\n")
